# based on https://dev.to/dariansampare/setting-up-docker-typescript-node-hot-reloading-code-changes-in-a-running-container-2b2f
version: '3.7'

services:
  # Backend container
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./api/src:/home/node/app/src
      - ./api/nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
   image: postgres:13
   container_name: postgres
   env_file:
    - ./api/.env
   ports:
    - "5432:5432"
   volumes:
    - "pgdata:/var/lib/postgresql/data"


  # Frontend Container

  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    container_name: ui
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - backend

volumes:
 pgdata:
